name: meals-bot
on:
  schedule:
    - cron: "30 23 * * *" # 07:30 CST 提醒
    - cron: "30 1 * * *"  # 09:30 CST 午餐汇总
    - cron: "30 5 * * *"  # 13:30 CST 提醒：晚餐&次日早餐
    - cron: "0 7 * * *"   # 15:00 CST 晚餐+次日早餐汇总
  workflow_dispatch:
    inputs:
      task:
        description: "Pick a task to run manually"
        required: true
        default: remind_am
        type: choice
        options: [remind_am, report_lunch, remind_pm, report_dinner, report_breakfast]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install requests

      # 07:30 提醒（自动拼 prefill_用餐日期=今天；LOCK_DATE=1 可锁定日期）
      - name: Remind AM (07:30 CST)
        if: |
          (github.event_name == 'schedule' && github.event.schedule == '30 23 * * *') ||
          (github.event_name == 'workflow_dispatch' && inputs.task == 'remind_am')
        run: python meals_bot.py
        env:
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: remind
          DATE_SHIFT_DAYS: "0"
          FORM_URL: ${{ secrets.FORM_URL }}
          DEADLINE_HHMM: "09:30"
          LOCK_DATE: ${{ secrets.LOCK_DATE }}

      # 09:30 午餐汇总（@ 指定 userID）
      - name: Report Lunch (09:30 CST)
        if: |
          (github.event_name == 'schedule' && github.event.schedule == '30 1 * * *') ||
          (github.event_name == 'workflow_dispatch' && inputs.task == 'report_lunch')
        run: python meals_bot.py
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          BITABLE_APP_TOKEN: ${{ secrets.BITABLE_APP_TOKEN }}
          BITABLE_TABLE_ID: ${{ secrets.BITABLE_TABLE_ID }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: report
          MEAL_KIND: lunch
          DATE_SHIFT_DAYS: "0"
          MENTION_USERIDS: ${{ secrets.MENTION_USERIDS }}

      # 13:30 提醒
      - name: Remind PM (13:30 CST)
        if: |
          (github.event_name == 'schedule' && github.event.schedule == '30 5 * * *') ||
          (github.event_name == 'workflow_dispatch' && inputs.task == 'remind_pm')
        run: python meals_bot.py
        env:
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: remind
          DATE_SHIFT_DAYS: "0"
          FORM_URL: ${{ secrets.FORM_URL }}
          DEADLINE_HHMM: "15:00"
          LOCK_DATE: ${{ secrets.LOCK_DATE }}

      # 15:00 晚餐汇总
      - name: Report Dinner (15:00 CST)
        if: |
          (github.event_name == 'schedule' && github.event.schedule == '0 7 * * *') ||
          (github.event_name == 'workflow_dispatch' && inputs.task == 'report_dinner')
        run: python meals_bot.py
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          BITABLE_APP_TOKEN: ${{ secrets.BITABLE_APP_TOKEN }}
          BITABLE_TABLE_ID: ${{ secrets.BITABLE_TABLE_ID }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: report
          MEAL_KIND: dinner
          DATE_SHIFT_DAYS: "0"
          MENTION_USERIDS: ${{ secrets.MENTION_USERIDS }}

      # 15:00 次日早餐汇总
      - name: Report Breakfast Tomorrow (15:00 CST)
        if: |
          (github.event_name == 'schedule' && github.event.schedule == '0 7 * * *') ||
          (github.event_name == 'workflow_dispatch' && inputs.task == 'report_breakfast')
        run: python meals_bot.py
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          BITABLE_APP_TOKEN: ${{ secrets.BITABLE_APP_TOKEN }}
          BITABLE_TABLE_ID: ${{ secrets.BITABLE_TABLE_ID }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: report
          MEAL_KIND: breakfast_next
          DATE_SHIFT_DAYS: "1"
          MENTION_USERIDS: ${{ secrets.MENTION_USERIDS }}
