name: meals
on:
  schedule:
    - cron: '30 23 * * *'  # 07:30 BJT (23:30 UTC previous day)
    - cron: '32 23 * * *'  # 07:32 BJT
    - cron: '30 1 * * *'   # 09:30 BJT
    - cron: '32 1 * * *'   # 09:32 BJT
    - cron: '30 5 * * *'   # 13:30 BJT
    - cron: '32 5 * * *'   # 13:32 BJT
    - cron: '0 7 * * *'    # 15:00 BJT
    - cron: '2 7 * * *'    # 15:02 BJT
  workflow_dispatch:
    inputs:
      task:
        description: 'Task to run (optional): lunch_reminder, lunch_report, dinner_reminder, dinner_report, breakfast_report'
        required: false
        default: ''
jobs:
  lunch_reminder:
    if: >
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'lunch_reminder' || github.event.inputs.task == '')) ||
      (github.event_name == 'schedule' && (contains(github.event.schedule, '30 23 * * *') || contains(github.event.schedule, '32 23 * * *')))
    runs-on: ubuntu-latest
    env:
      MODE: remind
      MEAL_KIND: lunch
      DATE_SHIFT_DAYS: 0
    steps:
      - name: Log task info
        run: |
          echo "Task: Lunch Order Reminder"
          echo "MODE=$MODE"
          echo "MEAL_KIND=$MEAL_KIND"
          echo "DATE_SHIFT_DAYS=$DATE_SHIFT_DAYS"
  lunch_report:
    if: >
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'lunch_report' || github.event.inputs.task == '')) ||
      (github.event_name == 'schedule' && (contains(github.event.schedule, '30 1 * * *') || contains(github.event.schedule, '32 1 * * *')))
    runs-on: ubuntu-latest
    env:
      MODE: report
      MEAL_KIND: lunch
      DATE_SHIFT_DAYS: 0
    steps:
      - name: Log task info
        run: |
          echo "Task: Lunch Summary"
          echo "MODE=$MODE"
          echo "MEAL_KIND=$MEAL_KIND"
          echo "DATE_SHIFT_DAYS=$DATE_SHIFT_DAYS"
  dinner_reminder:
    if: >
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'dinner_reminder' || github.event.inputs.task == '')) ||
      (github.event_name == 'schedule' && (contains(github.event.schedule, '30 5 * * *') || contains(github.event.schedule, '32 5 * * *')))
    runs-on: ubuntu-latest
    env:
      MODE: remind
      MEAL_KIND: dinner,breakfast_next
      DATE_SHIFT_DAYS: 0
    steps:
      - name: Log task info
        run: |
          echo "Task: Dinner & Next Day Breakfast Order Reminder"
          echo "MODE=$MODE"
          echo "MEAL_KIND=$MEAL_KIND"
          echo "DATE_SHIFT_DAYS=$DATE_SHIFT_DAYS"
  dinner_report:
    if: >
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'dinner_report' || github.event.inputs.task == '')) ||
      (github.event_name == 'schedule' && (contains(github.event.schedule, '0 7 * * *') || contains(github.event.schedule, '2 7 * * *')))
    runs-on: ubuntu-latest
    env:
      MODE: report
      MEAL_KIND: dinner
      DATE_SHIFT_DAYS: 0
    steps:
      - name: Log task info
        run: |
          echo "Task: Dinner Summary"
          echo "MODE=$MODE"
          echo "MEAL_KIND=$MEAL_KIND"
          echo "DATE_SHIFT_DAYS=$DATE_SHIFT_DAYS"
  breakfast_report:
    if: >
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'breakfast_report' || github.event.inputs.task == '')) ||
      (github.event_name == 'schedule' && (contains(github.event.schedule, '0 7 * * *') || contains(github.event.schedule, '2 7 * * *')))
    runs-on: ubuntu-latest
    env:
      MODE: report
      MEAL_KIND: breakfast_next
      DATE_SHIFT_DAYS: 0
    steps:
      - name: Log task info
        run: |
          echo "Task: Next Day Breakfast Summary"
          echo "MODE=$MODE"
          echo "MEAL_KIND=$MEAL_KIND"
          echo "DATE_SHIFT_DAYS=$DATE_SHIFT_DAYS"
