name: Automatic Meal Ordering Scheduler

on:
  schedule:
    # 每日07:30 (午餐提醒) + 07:32 备用
    - cron: '30 23 * * *'
    - cron: '32 23 * * *'
    # 每日09:30 (午餐汇总) + 09:32 备用
    - cron: '30 01 * * *'
    - cron: '32 01 * * *'
    # 每日13:30 (晚餐&次日早餐提醒) + 13:32 备用
    - cron: '30 05 * * *'
    - cron: '32 05 * * *'
    # 每日15:00 (晚餐汇总 & 次日早餐汇总) + 15:02 备用
    - cron: '00 07 * * *'
    - cron: '02 07 * * *'
  workflow_dispatch:
    inputs:
      task:
        description: '选择手动运行的任务（remind_lunch/summary_lunch/remind_dinner_breakfast/summary_dinner/summary_breakfast/all）'
        required: true
        type: choice
        options:
          - remind_lunch
          - summary_lunch
          - remind_dinner_breakfast
          - summary_dinner
          - summary_breakfast
          - all

jobs:
  remind_lunch:
    runs-on: ubuntu-latest
    # 仅在每日07:30主/备用触发或手动选择remind_lunch时运行
    if: github.event_name == 'schedule' && (github.event.schedule == '30 23 * * *' || github.event.schedule == '32 23 * * *') || github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'all' || github.event.inputs.task == 'remind_lunch')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 发送午餐订餐提醒
        run: echo "Executing lunch order reminder..."

  summary_lunch:
    runs-on: ubuntu-latest
    # 仅在每日09:30主/备用触发或手动选择summary_lunch时运行
    if: github.event_name == 'schedule' && (github.event.schedule == '30 01 * * *' || github.event.schedule == '32 01 * * *') || github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'all' || github.event.inputs.task == 'summary_lunch')
    env:
      SEND_WINDOW_MIN: 20  # 最长发送窗口20分钟
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 发送午餐订餐汇总通知
        run: echo "Executing lunch order summary report..."

  remind_dinner_breakfast:
    runs-on: ubuntu-latest
    # 仅在每日13:30主/备用触发或手动选择remind_dinner_breakfast时运行
    if: github.event_name == 'schedule' && (github.event.schedule == '30 05 * * *' || github.event.schedule == '32 05 * * *') || github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'all' || github.event.inputs.task == 'remind_dinner_breakfast')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 发送晚餐及次日早餐订餐提醒
        run: echo "Executing dinner & next-day breakfast order reminder..."

  summary_dinner:
    runs-on: ubuntu-latest
    # 仅在每日15:00主/备用触发或手动选择summary_dinner时运行
    if: github.event_name == 'schedule' && (github.event.schedule == '00 07 * * *' || github.event.schedule == '02 07 * * *') || github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'all' || github.event.inputs.task == 'summary_dinner')
    env:
      SEND_WINDOW_MIN: 20  # 最长发送窗口20分钟
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 发送晚餐订餐汇总通知
        run: echo "Executing dinner order summary report..."

  summary_breakfast:
    runs-on: ubuntu-latest
    # 仅在每日15:00主/备用触发或手动选择summary_breakfast时运行
    if: github.event_name == 'schedule' && (github.event.schedule == '00 07 * * *' || github.event.schedule == '02 07 * * *') || github.event_name == 'workflow_dispatch' && (github.event.inputs.task == 'all' || github.event.inputs.task == 'summary_breakfast')
    env:
      SEND_WINDOW_MIN: 20  # 最长发送窗口20分钟
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 发送次日早餐订餐汇总通知
        run: echo "Executing next-day breakfast order summary report..."
