name: meals-bot

on:
  schedule:
    - cron: "30 23 * * *" # 07:30 BJT 提醒(主)
    - cron: "32 23 * * *" # 07:32 BJT 提醒(备)
    - cron: "30 1 * * *"  # 09:30 BJT 午餐汇总(主)
    - cron: "32 1 * * *"  # 09:32 BJT 午餐汇总(备)
    - cron: "30 5 * * *"  # 13:30 BJT 提醒(主)
    - cron: "32 5 * * *"  # 13:32 BJT 提醒(备)
    - cron: "0 7 * * *"   # 15:00 BJT 晚餐/早餐汇总(主)
    - cron: "2 7 * * *"   # 15:02 BJT 晚餐/早餐汇总(备)
  workflow_dispatch:
    inputs:
      task:
        description: "手动运行: remind_lunch, report_lunch, remind_pm, report_dinner, report_breakfast"
        required: true
        default: remind_lunch
        type: choice
        options: [remind_lunch, report_lunch, remind_pm, report_dinner, report_breakfast]

jobs:
  remind_lunch:
    name: Remind Lunch (07:30/07:32)
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'schedule' && (contains(github.event.schedule, '30 23') || contains(github.event.schedule, '32 23'))) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'remind_lunch')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install --no-cache-dir requests
      - name: Run remind (lunch)
        run: python meals_bot.py
        env:
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: remind
          DATE_SHIFT_DAYS: "0"
          FORM_URL: ${{ secrets.FORM_URL }}
          DEADLINE_HHMM: "09:30"
          LOCK_DATE: ${{ secrets.LOCK_DATE }}

  report_lunch:
    name: Report Lunch (09:30/09:32)
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'schedule' && (contains(github.event.schedule, '30 1') || contains(github.event.schedule, '32 1'))) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'report_lunch')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install --no-cache-dir requests
      - name: Run report (lunch)
        run: python meals_bot.py
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          BITABLE_APP_TOKEN: ${{ secrets.BITABLE_APP_TOKEN }}
          BITABLE_TABLE_ID: ${{ secrets.BITABLE_TABLE_ID }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: report
          MEAL_KIND: lunch
          DATE_SHIFT_DAYS: "0"
          MENTION_USERIDS: ${{ secrets.MENTION_USERIDS }}

  remind_pm:
    name: Remind Dinner & Breakfast (13:30/13:32)
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'schedule' && (contains(github.event.schedule, '30 5') || contains(github.event.schedule, '32 5'))) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'remind_pm')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install --no-cache-dir requests
      - name: Run remind (dinner & breakfast_next)
        run: python meals_bot.py
        env:
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: remind
          DATE_SHIFT_DAYS: "0"
          FORM_URL: ${{ secrets.FORM_URL }}
          DEADLINE_HHMM: "15:00"
          LOCK_DATE: ${{ secrets.LOCK_DATE }}

  report_dinner:
    name: Report Dinner (15:00/15:02)
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'schedule' && (contains(github.event.schedule, '0 7') || contains(github.event.schedule, '2 7'))) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'report_dinner')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install --no-cache-dir requests
      - name: Run report (dinner)
        run: python meals_bot.py
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          BITABLE_APP_TOKEN: ${{ secrets.BITABLE_APP_TOKEN }}
          BITABLE_TABLE_ID: ${{ secrets.BITABLE_TABLE_ID }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: report
          MEAL_KIND: dinner
          DATE_SHIFT_DAYS: "0"
          MENTION_USERIDS: ${{ secrets.MENTION_USERIDS }}

  report_breakfast:
    name: Report Breakfast Tomorrow (15:00/15:02)
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'schedule' && (contains(github.event.schedule, '0 7') || contains(github.event.schedule, '2 7'))) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'report_breakfast')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install --no-cache-dir requests
      - name: Run report (breakfast_next)
        run: python meals_bot.py
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          BITABLE_APP_TOKEN: ${{ secrets.BITABLE_APP_TOKEN }}
          BITABLE_TABLE_ID: ${{ secrets.BITABLE_TABLE_ID }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          TIMEZONE: Asia/Shanghai
          MODE: report
          MEAL_KIND: breakfast_next
          DATE_SHIFT_DAYS: "1"
          MENTION_USERIDS: ${{ secrets.MENTION_USERIDS }}
