name: meals-bot-scheduling

on:
  schedule:
    # 北京时间 (Asia/Shanghai) 07:30 主触发 (UTC 23:30)
    - cron: '30 23 * * *'
    # 北京时间 07:32 备用触发 (UTC 23:32)
    - cron: '32 23 * * *'
    # 北京时间 09:30 主触发 (UTC 01:30)
    - cron: '30 1 * * *'
    # 北京时间 09:32 备用触发 (UTC 01:32)
    - cron: '32 1 * * *'
    # 北京时间 13:30 主触发 (UTC 05:30)
    - cron: '30 5 * * *'
    # 北京时间 13:32 备用触发 (UTC 05:32)
    - cron: '32 5 * * *'
    # 北京时间 15:00 主触发 (UTC 07:00)
    - cron: '0 7 * * *'
    # 北京时间 15:02 备用触发 (UTC 07:02)
    - cron: '2 7 * * *'
  workflow_dispatch:
    inputs:
      task:
        description: '任务类型 (remind_lunch, summary_lunch, remind_dinner_breakfast, summary_dinner, summary_breakfast)'
        required: true
        default: 'remind_lunch'

jobs:
  remind_lunch:
    name: Remind Lunch
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - id: check_time
        name: Check schedule or task (Remind Lunch)
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_TASK: ${{ github.event.inputs.task }}
        run: |
          TIME=$(TZ="Asia/Shanghai" date +'%H:%M')
          echo "Event: $EVENT_NAME, Time: $TIME, Input Task: $INPUT_TASK"
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
              if [ "$INPUT_TASK" != "remind_lunch" ]; then
                  echo "skip=true" >> $GITHUB_OUTPUT
              else
                  echo "skip=false" >> $GITHUB_OUTPUT
              fi
          else
              if [ "$TIME" = "07:30" ] || [ "$TIME" = "07:32" ]; then
                  echo "skip=false" >> $GITHUB_OUTPUT
              else
                  echo "skip=true" >> $GITHUB_OUTPUT
              fi
          fi
      - name: Run Remind Lunch
        if: steps.check_time.outputs.skip == 'false'
        run: |
          python meals_bot.py remind_lunch

  summary_lunch:
    name: Summary Lunch
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - id: check_time
        name: Check schedule or task (Summary Lunch)
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_TASK: ${{ github.event.inputs.task }}
        run: |
          TIME=$(TZ="Asia/Shanghai" date +'%H:%M')
          echo "Event: $EVENT_NAME, Time: $TIME, Input Task: $INPUT_TASK"
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
              if [ "$INPUT_TASK" != "summary_lunch" ]; then
                  echo "skip=true" >> $GITHUB_OUTPUT
              else
                  echo "skip=false" >> $GITHUB_OUTPUT
              fi
          else
              if [ "$TIME" = "09:30" ] || [ "$TIME" = "09:32" ]; then
                  echo "skip=false" >> $GITHUB_OUTPUT
              else
                  echo "skip=true" >> $GITHUB_OUTPUT
              fi
          fi
      - name: Run Summary Lunch
        if: steps.check_time.outputs.skip == 'false'
        run: |
          python meals_bot.py summary_lunch

  remind_dinner_breakfast:
    name: Remind Dinner/Breakfast
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - id: check_time
        name: Check schedule or task (Remind Dinner/Breakfast)
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_TASK: ${{ github.event.inputs.task }}
        run: |
          TIME=$(TZ="Asia/Shanghai" date +'%H:%M')
          echo "Event: $EVENT_NAME, Time: $TIME, Input Task: $INPUT_TASK"
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
              if [ "$INPUT_TASK" != "remind_dinner_breakfast" ]; then
                  echo "skip=true" >> $GITHUB_OUTPUT
              else
                  echo "skip=false" >> $GITHUB_OUTPUT
              fi
          else
              if [ "$TIME" = "13:30" ] || [ "$TIME" = "13:32" ]; then
                  echo "skip=false" >> $GITHUB_OUTPUT
              else
                  echo "skip=true" >> $GITHUB_OUTPUT
              fi
          fi
      - name: Run Remind Dinner/Breakfast
        if: steps.check_time.outputs.skip == 'false'
        run: |
          python meals_bot.py remind_dinner_breakfast

  summary_dinner:
    name: Summary Dinner
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - id: check_time
        name: Check schedule or task (Summary Dinner)
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_TASK: ${{ github.event.inputs.task }}
        run: |
          TIME=$(TZ="Asia/Shanghai" date +'%H:%M')
          echo "Event: $EVENT_NAME, Time: $TIME, Input Task: $INPUT_TASK"
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
              if [ "$INPUT_TASK" != "summary_dinner" ]; then
                  echo "skip=true" >> $GITHUB_OUTPUT
              else
                  echo "skip=false" >> $GITHUB_OUTPUT
              fi
          else
              if [ "$TIME" = "15:00" ] || [ "$TIME" = "15:02" ]; then
                  echo "skip=false" >> $GITHUB_OUTPUT
              else
                  echo "skip=true" >> $GITHUB_OUTPUT
              fi
          fi
      - name: Run Summary Dinner
        if: steps.check_time.outputs.skip == 'false'
        run: |
          python meals_bot.py summary_dinner

  summary_breakfast:
    name: Summary Breakfast
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - id: check_time
        name: Check schedule or task (Summary Breakfast)
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_TASK: ${{ github.event.inputs.task }}
        run: |
          TIME=$(TZ="Asia/Shanghai" date +'%H:%M')
          echo "Event: $EVENT_NAME, Time: $TIME, Input Task: $INPUT_TASK"
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
              if [ "$INPUT_TASK" != "summary_breakfast" ]; then
                  echo "skip=true" >> $GITHUB_OUTPUT
              else
                  echo "skip=false" >> $GITHUB_OUTPUT
              fi
          else
              if [ "$TIME" = "15:00" ] || [ "$TIME" = "15:02" ]; then
                  echo "skip=false" >> $GITHUB_OUTPUT
              else
                  echo "skip=true" >> $GITHUB_OUTPUT
              fi
          fi
      - name: Run Summary Breakfast
        if: steps.check_time.outputs.skip == 'false'
        run: |
          python meals_bot.py summary_breakfast
